on: pull_request

name: PullRequest
jobs:
  test:
    name: UnitTest
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1.0.2
        id: carthage
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          carthage update --platform iOS --cache-builds && exit ${PIPESTATUS[0]}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}

      - name: Build and test
        run: |
          xcodebuild clean test -workspace SwiftCommunity.xcworkspace -scheme SwiftCommunity -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -derivedDataPath ./.build/DerivedData | xcpretty -c && exit ${PIPESTATUS[0]}
          bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
        env:
          destination: ${{ matrix.destination }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Danger
        run: |
          npm install -g danger@7.1.4
          swift run danger-swift ci --dangerfile Dangerfile.swift --id swiftlint
          swift run danger-swift ci --dangerfile CodeCoverageDangerfile.swift --id codecoverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
